In [1]:
blocks= ["didihat","ganaolihat","munsiyari","kanalichina"]
for block in blocks:
    print("UKIHDP review for:", block)

UKIHDP review for: didihat
UKIHDP review for: ganaolihat
UKIHDP review for: munsiyari
UKIHDP review for: kanalichina

In [7]:
blocks= ["didihat","ganaolihat","munsiyari","kanalichina"]
for block in blocks:
    print(block)  
    print("monthly report pending")

didihat
monthly report pending
ganaolihat
monthly report pending
munsiyari
monthly report pending
kanalichina
monthly report pending

In [4]:
farmers= [12,18,25,30]
for number in farmers:
    print(number*2)

24
36
50
60

In [9]:
farmer={
    "name":"geeta",
    "block":"gangolihat",
    "crop":"apple",
    "area":1.2
}
farmer

{'name': 'geeta', 'block': 'gangolihat', 'crop': 'apple', 'area': 1.2}

In [11]:
print(farmer["name"])

geeta

In [18]:
print("farmer",farmer["name"],"is growing",farmer["crop"])

farmer geeta is growing apple

In [19]:
farmer["crop"]= "malta"

In [21]:
print(farmer)

{'name': 'geeta', 'block': 'gangolihat', 'crop': 'malta', 'area': 1.2}

In [58]:
farmers=[
    {"name":"mohan", "block":"didihat","crop":"potato"},
    {"name":"geeta", "block":"gangolihat","crop":"apple"},
    {"name":"sohan","block":"munsiyari","crop":"pea"}
]
farmers

[{'name': 'mohan', 'block': 'didihat', 'crop': 'potato'},
 {'name': 'geeta', 'block': 'gangolihat', 'crop': 'apple'},
 {'name': 'sohan', 'block': 'munsiyari', 'crop': 'pea'}]

In [59]:
farmers[0]["mob no."] = "12"
farmers[1]["mob no."] = "13"
farmers[2]["mob no."] = "14"
(farmers)

[{'name': 'mohan', 'block': 'didihat', 'crop': 'potato', 'mob no.': '12'},
 {'name': 'geeta', 'block': 'gangolihat', 'crop': 'apple', 'mob no.': '13'},
 {'name': 'sohan', 'block': 'munsiyari', 'crop': 'pea', 'mob no.': '14'}]

In [34]:
for farmer in farmers:
    print("farmer:", farmer["name"])
    print("block:", farmer["block"])
    print("crop:", farmer["crop"])
    print("--------")

farmer: mohan
block: didihat
crop: potato
--------
farmer: geeta
block: gangolihat
crop: apple
--------
farmer: sohan
block: munsiyari
crop: pea
--------

In [43]:
farmers={
    "name":["mohan","geeta","sohan"],
    "block":["didihat","gangolihat","munsiyari"],
    "crop":["potato","apple","pea"]
}
farmers

{'name': ['mohan', 'geeta', 'sohan'],
 'block': ['didihat', 'gangolihat', 'munsiyari'],
 'crop': ['potato', 'apple', 'pea']}

In [44]:
farmers["mob no.:"]= [12,25,23]
farmers

{'name': ['mohan', 'geeta', 'sohan'],
 'block': ['didihat', 'gangolihat', 'munsiyari'],
 'crop': ['potato', 'apple', 'pea'],
 'mob no.:': [12, 25, 23]}

In [30]:
import pandas as pd
farmers={
    "name":["mohan","geeta","sohan"],
    "block":["didihat","gangolihat","munsiyari"],
    "crop":["potato","apple","pea"]
}
df=pd.DataFrame(farmers)
df

    name       block    crop
0  mohan     didihat  potato
1  geeta  gangolihat   apple
2  sohan   munsiyari     pea

In [39]:
df["mob no."]= [25,26,27]
df

    name       block    crop  mob no.
0  mohan     didihat  potato       25
1  geeta  gangolihat   apple       26
2  sohan   munsiyari     pea       27